#ifndef TOKEN_TABLE_H
#define TOKEN_TABLE_H
#define ID                1
#define INT_CONSTANT      2
#define BOOL_CONSTANT     3 
#define STRING_CONSTANT   4
#define INT               5
#define SHORT             6
#define LONG              7
#define FLOAT             8
#define DOUBLE            9
#define CHAR              10
#define STRUCT            11
#define UNION             12
#define ENUM              13
#define TYPEDEF           14
#define CONST             15
#define UNSIGNED          16
#define SIGNED            17
#define EXTERN            18
#define VOID              19
#define IF                20
#define ELSE              21
#define SWITCH            22
#define CASE              23
#define FOR               24
#define DO                25
#define WHILE             26
#define CONTINUE          27
#define BREAK             28
#define DEFAULT           29
#define SIZEOF            30
#define RETURN            31
#define COMMA             32
#define ";"]              33
#define ":"]              34
#define "+"]              35
#define "-"]              36
#define "*"]              37
#define "/"]              38
#define "%"]              39
#define "++"]             40
#define "--"]             41
#define "!"]              42
#define "?"]              43
#define "("]              44
#define ")"]              45
#define "&"]              46
#define "|"]              47
#define "="]              48
#define ">"]              49
#define ">="]             50
#define "<"]              51
#define "<="]             52
#define "=="]             53
#define "!="]             54
#define "||"]             55
#define "&&"]             56
#define "^"]              57
#define "["]              58
#define "]"]              59
#define "{"]              60
#define "}"]              61
#define "'"]              62
#define "\""]             63
#define "octal_constant"] 64
#define "hex_constant"]   65
#define "+="]             66
#define "-="]             67
#define "*="]             68
#define "/="]             69
#endif